//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.08 at 03:36:14 PM MST 
//


package nl.wldelft.fews;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArchiveTimeSeriesSetComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArchiveTimeSeriesSetComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="moduleInstanceId" type="{http://www.wldelft.nl/fews/PI}idStringType"/&gt;
 *         &lt;element name="parameterId" type="{http://www.wldelft.nl/fews/PI}idStringType"/&gt;
 *         &lt;element name="qualifierId" type="{http://www.wldelft.nl/fews/PI}idStringType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="locationId" type="{http://www.wldelft.nl/fews/PI}idStringType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="timeSeriesType" type="{http://www.wldelft.nl/fews/PI}timeSeriesTypeEnumStringType"/&gt;
 *         &lt;element name="timeStep" type="{http://www.wldelft.nl/fews/PI}TimeStepComplexType"/&gt;
 *         &lt;element name="ensembleId" type="{http://www.wldelft.nl/fews/PI}idStringType" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArchiveTimeSeriesSetComplexType", propOrder = {
    "moduleInstanceId",
    "parameterId",
    "qualifierId",
    "locationId",
    "timeSeriesType",
    "timeStep",
    "ensembleId"
})
public class ArchiveTimeSeriesSetComplexType {

    @XmlElement(required = true)
    protected String moduleInstanceId;
    @XmlElement(required = true)
    protected String parameterId;
    protected List<String> qualifierId;
    @XmlElement(required = true)
    protected List<String> locationId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TimeSeriesTypeEnumStringType timeSeriesType;
    @XmlElement(required = true)
    protected TimeStepComplexType timeStep;
    protected String ensembleId;

    /**
     * Gets the value of the moduleInstanceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModuleInstanceId() {
        return moduleInstanceId;
    }

    /**
     * Sets the value of the moduleInstanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModuleInstanceId(String value) {
        this.moduleInstanceId = value;
    }

    /**
     * Gets the value of the parameterId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterId() {
        return parameterId;
    }

    /**
     * Sets the value of the parameterId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterId(String value) {
        this.parameterId = value;
    }

    /**
     * Gets the value of the qualifierId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualifierId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualifierId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getQualifierId() {
        if (qualifierId == null) {
            qualifierId = new ArrayList<String>();
        }
        return this.qualifierId;
    }

    /**
     * Gets the value of the locationId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the locationId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocationId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLocationId() {
        if (locationId == null) {
            locationId = new ArrayList<String>();
        }
        return this.locationId;
    }

    /**
     * Gets the value of the timeSeriesType property.
     * 
     * @return
     *     possible object is
     *     {@link TimeSeriesTypeEnumStringType }
     *     
     */
    public TimeSeriesTypeEnumStringType getTimeSeriesType() {
        return timeSeriesType;
    }

    /**
     * Sets the value of the timeSeriesType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSeriesTypeEnumStringType }
     *     
     */
    public void setTimeSeriesType(TimeSeriesTypeEnumStringType value) {
        this.timeSeriesType = value;
    }

    /**
     * Gets the value of the timeStep property.
     * 
     * @return
     *     possible object is
     *     {@link TimeStepComplexType }
     *     
     */
    public TimeStepComplexType getTimeStep() {
        return timeStep;
    }

    /**
     * Sets the value of the timeStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeStepComplexType }
     *     
     */
    public void setTimeStep(TimeStepComplexType value) {
        this.timeStep = value;
    }

    /**
     * Gets the value of the ensembleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnsembleId() {
        return ensembleId;
    }

    /**
     * Sets the value of the ensembleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnsembleId(String value) {
        this.ensembleId = value;
    }

}
