//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.08 at 03:36:14 PM MST 
//


package nl.wldelft.fews;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeoDatumEnumStringType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GeoDatumEnumStringType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="LOCAL"/&gt;
 *     &lt;enumeration value="WGS 1984"/&gt;
 *     &lt;enumeration value="Ordnance Survey Great Britain 1936"/&gt;
 *     &lt;enumeration value="TWD 1967"/&gt;
 *     &lt;enumeration value="Gauss Krueger Meridian2"/&gt;
 *     &lt;enumeration value="Gauss Krueger Meridian3"/&gt;
 *     &lt;enumeration value="Gauss Krueger Austria M34"/&gt;
 *     &lt;enumeration value="Gauss Krueger Austria M31"/&gt;
 *     &lt;enumeration value="Rijks Driehoekstelsel"/&gt;
 *     &lt;enumeration value="JRC"/&gt;
 *     &lt;enumeration value="DWD"/&gt;
 *     &lt;enumeration value="KNMI Radar"/&gt;
 *     &lt;enumeration value="CH1903"/&gt;
 *     &lt;enumeration value="PAK1"/&gt;
 *     &lt;enumeration value="PAK2"/&gt;
 *     &lt;enumeration value="SVY21"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "GeoDatumEnumStringType")
@XmlEnum
public enum GeoDatumEnumStringType {

    LOCAL("LOCAL"),
    @XmlEnumValue("WGS 1984")
    WGS_1984("WGS 1984"),
    @XmlEnumValue("Ordnance Survey Great Britain 1936")
    ORDNANCE_SURVEY_GREAT_BRITAIN_1936("Ordnance Survey Great Britain 1936"),
    @XmlEnumValue("TWD 1967")
    TWD_1967("TWD 1967"),
    @XmlEnumValue("Gauss Krueger Meridian2")
    GAUSS_KRUEGER_MERIDIAN_2("Gauss Krueger Meridian2"),
    @XmlEnumValue("Gauss Krueger Meridian3")
    GAUSS_KRUEGER_MERIDIAN_3("Gauss Krueger Meridian3"),
    @XmlEnumValue("Gauss Krueger Austria M34")
    GAUSS_KRUEGER_AUSTRIA_M_34("Gauss Krueger Austria M34"),
    @XmlEnumValue("Gauss Krueger Austria M31")
    GAUSS_KRUEGER_AUSTRIA_M_31("Gauss Krueger Austria M31"),
    @XmlEnumValue("Rijks Driehoekstelsel")
    RIJKS_DRIEHOEKSTELSEL("Rijks Driehoekstelsel"),
    JRC("JRC"),
    DWD("DWD"),
    @XmlEnumValue("KNMI Radar")
    KNMI_RADAR("KNMI Radar"),
    @XmlEnumValue("CH1903")
    CH_1903("CH1903"),
    @XmlEnumValue("PAK1")
    PAK_1("PAK1"),
    @XmlEnumValue("PAK2")
    PAK_2("PAK2"),
    @XmlEnumValue("SVY21")
    SVY_21("SVY21");
    private final String value;

    GeoDatumEnumStringType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GeoDatumEnumStringType fromValue(String v) {
        for (GeoDatumEnumStringType c: GeoDatumEnumStringType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
