//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.08 at 03:36:14 PM MST 
//


package nl.wldelft.fews;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * The header is used to specify the link to the location
 *                 and the contents
 * 
 * <p>Java class for HeaderComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeaderComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="type" type="{http://www.wldelft.nl/fews/PI}timeSeriesType"/&gt;
 *         &lt;element name="moduleInstanceId" type="{http://www.wldelft.nl/fews/PI}idStringType" minOccurs="0"/&gt;
 *         &lt;element name="locationId" type="{http://www.wldelft.nl/fews/PI}LocationIdSimpleType"/&gt;
 *         &lt;element name="parameterId" type="{http://www.wldelft.nl/fews/PI}ParameterSimpleType"/&gt;
 *         &lt;element name="domainParameterId" type="{http://www.wldelft.nl/fews/PI}ParameterSimpleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="qualifierId" type="{http://www.wldelft.nl/fews/PI}idString" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;sequence minOccurs="0"&gt;
 *           &lt;element name="ensembleId" type="{http://www.wldelft.nl/fews/PI}idString" minOccurs="0"/&gt;
 *           &lt;choice&gt;
 *             &lt;element name="ensembleMemberIndex" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/&gt;
 *             &lt;element name="ensembleMemberId" type="{http://www.wldelft.nl/fews/PI}idString"/&gt;
 *           &lt;/choice&gt;
 *         &lt;/sequence&gt;
 *         &lt;element name="timeStep" type="{http://www.wldelft.nl/fews/PI}TimeStepComplexType"/&gt;
 *         &lt;element name="startDate" type="{http://www.wldelft.nl/fews/PI}DateTimeComplexType"/&gt;
 *         &lt;element name="endDate" type="{http://www.wldelft.nl/fews/PI}DateTimeComplexType"/&gt;
 *         &lt;element name="forecastDate" type="{http://www.wldelft.nl/fews/PI}DateTimeComplexType" minOccurs="0"/&gt;
 *         &lt;element name="missVal" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="longName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="stationName" type="{http://www.wldelft.nl/fews/PI}nameString" minOccurs="0"/&gt;
 *         &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="lon" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="z" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="units" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="domainAxis" type="{http://www.wldelft.nl/fews/PI}DomainAxisComplexType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="sourceOrganisation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sourceSystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fileDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="creationTime" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/&gt;
 *         &lt;element name="region" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="thresholds" type="{http://www.wldelft.nl/fews/PI}ThresholdComplexType" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.wldelft.nl/fews/PI}StatisticsGroup" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeaderComplexType", propOrder = {
    "type",
    "moduleInstanceId",
    "locationId",
    "parameterId",
    "domainParameterId",
    "qualifierId",
    "ensembleId",
    "ensembleMemberIndex",
    "ensembleMemberId",
    "timeStep",
    "startDate",
    "endDate",
    "forecastDate",
    "missVal",
    "longName",
    "stationName",
    "lat",
    "lon",
    "x",
    "y",
    "z",
    "units",
    "domainAxis",
    "sourceOrganisation",
    "sourceSystem",
    "fileDescription",
    "creationDate",
    "creationTime",
    "region",
    "thresholds",
    "firstValueTime",
    "lastValueTime",
    "maxValue",
    "minValue",
    "valueCount"
})
public class HeaderComplexType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TimeSeriesType type;
    protected String moduleInstanceId;
    @XmlElement(required = true)
    protected String locationId;
    @XmlElement(required = true)
    protected String parameterId;
    protected List<String> domainParameterId;
    protected List<String> qualifierId;
    protected String ensembleId;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger ensembleMemberIndex;
    protected String ensembleMemberId;
    @XmlElement(required = true)
    protected TimeStepComplexType timeStep;
    @XmlElement(required = true)
    protected DateTimeComplexType startDate;
    @XmlElement(required = true)
    protected DateTimeComplexType endDate;
    protected DateTimeComplexType forecastDate;
    @XmlElement(defaultValue = "NaN")
    protected double missVal;
    protected String longName;
    protected String stationName;
    protected Double lat;
    protected Double lon;
    protected Double x;
    protected Double y;
    protected Double z;
    protected String units;
    protected List<DomainAxisComplexType> domainAxis;
    protected String sourceOrganisation;
    protected String sourceSystem;
    protected String fileDescription;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar creationDate;
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar creationTime;
    protected String region;
    protected ThresholdComplexType thresholds;
    protected DateTimeComplexType firstValueTime;
    protected DateTimeComplexType lastValueTime;
    protected Float maxValue;
    protected Float minValue;
    protected Integer valueCount;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TimeSeriesType }
     *     
     */
    public TimeSeriesType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSeriesType }
     *     
     */
    public void setType(TimeSeriesType value) {
        this.type = value;
    }

    /**
     * Gets the value of the moduleInstanceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModuleInstanceId() {
        return moduleInstanceId;
    }

    /**
     * Sets the value of the moduleInstanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModuleInstanceId(String value) {
        this.moduleInstanceId = value;
    }

    /**
     * Gets the value of the locationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationId() {
        return locationId;
    }

    /**
     * Sets the value of the locationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationId(String value) {
        this.locationId = value;
    }

    /**
     * Gets the value of the parameterId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterId() {
        return parameterId;
    }

    /**
     * Sets the value of the parameterId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterId(String value) {
        this.parameterId = value;
    }

    /**
     * Gets the value of the domainParameterId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the domainParameterId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDomainParameterId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDomainParameterId() {
        if (domainParameterId == null) {
            domainParameterId = new ArrayList<String>();
        }
        return this.domainParameterId;
    }

    /**
     * Gets the value of the qualifierId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualifierId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualifierId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getQualifierId() {
        if (qualifierId == null) {
            qualifierId = new ArrayList<String>();
        }
        return this.qualifierId;
    }

    /**
     * Gets the value of the ensembleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnsembleId() {
        return ensembleId;
    }

    /**
     * Sets the value of the ensembleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnsembleId(String value) {
        this.ensembleId = value;
    }

    /**
     * Gets the value of the ensembleMemberIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEnsembleMemberIndex() {
        return ensembleMemberIndex;
    }

    /**
     * Sets the value of the ensembleMemberIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEnsembleMemberIndex(BigInteger value) {
        this.ensembleMemberIndex = value;
    }

    /**
     * Gets the value of the ensembleMemberId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnsembleMemberId() {
        return ensembleMemberId;
    }

    /**
     * Sets the value of the ensembleMemberId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnsembleMemberId(String value) {
        this.ensembleMemberId = value;
    }

    /**
     * Gets the value of the timeStep property.
     * 
     * @return
     *     possible object is
     *     {@link TimeStepComplexType }
     *     
     */
    public TimeStepComplexType getTimeStep() {
        return timeStep;
    }

    /**
     * Sets the value of the timeStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeStepComplexType }
     *     
     */
    public void setTimeStep(TimeStepComplexType value) {
        this.timeStep = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeComplexType }
     *     
     */
    public DateTimeComplexType getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeComplexType }
     *     
     */
    public void setStartDate(DateTimeComplexType value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeComplexType }
     *     
     */
    public DateTimeComplexType getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeComplexType }
     *     
     */
    public void setEndDate(DateTimeComplexType value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the forecastDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeComplexType }
     *     
     */
    public DateTimeComplexType getForecastDate() {
        return forecastDate;
    }

    /**
     * Sets the value of the forecastDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeComplexType }
     *     
     */
    public void setForecastDate(DateTimeComplexType value) {
        this.forecastDate = value;
    }

    /**
     * Gets the value of the missVal property.
     * 
     */
    public double getMissVal() {
        return missVal;
    }

    /**
     * Sets the value of the missVal property.
     * 
     */
    public void setMissVal(double value) {
        this.missVal = value;
    }

    /**
     * Gets the value of the longName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongName() {
        return longName;
    }

    /**
     * Sets the value of the longName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongName(String value) {
        this.longName = value;
    }

    /**
     * Gets the value of the stationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * Sets the value of the stationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationName(String value) {
        this.stationName = value;
    }

    /**
     * Gets the value of the lat property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLat(Double value) {
        this.lat = value;
    }

    /**
     * Gets the value of the lon property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLon() {
        return lon;
    }

    /**
     * Sets the value of the lon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLon(Double value) {
        this.lon = value;
    }

    /**
     * Gets the value of the x property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setX(Double value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setY(Double value) {
        this.y = value;
    }

    /**
     * Gets the value of the z property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getZ() {
        return z;
    }

    /**
     * Sets the value of the z property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setZ(Double value) {
        this.z = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnits(String value) {
        this.units = value;
    }

    /**
     * Gets the value of the domainAxis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the domainAxis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDomainAxis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DomainAxisComplexType }
     * 
     * 
     */
    public List<DomainAxisComplexType> getDomainAxis() {
        if (domainAxis == null) {
            domainAxis = new ArrayList<DomainAxisComplexType>();
        }
        return this.domainAxis;
    }

    /**
     * Gets the value of the sourceOrganisation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceOrganisation() {
        return sourceOrganisation;
    }

    /**
     * Sets the value of the sourceOrganisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceOrganisation(String value) {
        this.sourceOrganisation = value;
    }

    /**
     * Gets the value of the sourceSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceSystem() {
        return sourceSystem;
    }

    /**
     * Sets the value of the sourceSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceSystem(String value) {
        this.sourceSystem = value;
    }

    /**
     * Gets the value of the fileDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileDescription() {
        return fileDescription;
    }

    /**
     * Sets the value of the fileDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileDescription(String value) {
        this.fileDescription = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the creationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationTime(XMLGregorianCalendar value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the thresholds property.
     * 
     * @return
     *     possible object is
     *     {@link ThresholdComplexType }
     *     
     */
    public ThresholdComplexType getThresholds() {
        return thresholds;
    }

    /**
     * Sets the value of the thresholds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThresholdComplexType }
     *     
     */
    public void setThresholds(ThresholdComplexType value) {
        this.thresholds = value;
    }

    /**
     * Gets the value of the firstValueTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeComplexType }
     *     
     */
    public DateTimeComplexType getFirstValueTime() {
        return firstValueTime;
    }

    /**
     * Sets the value of the firstValueTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeComplexType }
     *     
     */
    public void setFirstValueTime(DateTimeComplexType value) {
        this.firstValueTime = value;
    }

    /**
     * Gets the value of the lastValueTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeComplexType }
     *     
     */
    public DateTimeComplexType getLastValueTime() {
        return lastValueTime;
    }

    /**
     * Sets the value of the lastValueTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeComplexType }
     *     
     */
    public void setLastValueTime(DateTimeComplexType value) {
        this.lastValueTime = value;
    }

    /**
     * Gets the value of the maxValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMaxValue() {
        return maxValue;
    }

    /**
     * Sets the value of the maxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMaxValue(Float value) {
        this.maxValue = value;
    }

    /**
     * Gets the value of the minValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMinValue() {
        return minValue;
    }

    /**
     * Sets the value of the minValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMinValue(Float value) {
        this.minValue = value;
    }

    /**
     * Gets the value of the valueCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getValueCount() {
        return valueCount;
    }

    /**
     * Sets the value of the valueCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setValueCount(Integer value) {
        this.valueCount = value;
    }

}
