//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.08 at 03:36:14 PM MST 
//


package nl.wldelft.fews;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Any number of parameters > 0
 * 
 * <p>Java class for ModelParameterComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModelParameterComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="description" type="{http://www.wldelft.nl/fews/PI}commentString" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="dblValue" type="{http://www.wldelft.nl/fews/PI}doubleStringType"/&gt;
 *           &lt;element name="intValue" type="{http://www.wldelft.nl/fews/PI}intStringType"/&gt;
 *           &lt;element name="boolValue" type="{http://www.wldelft.nl/fews/PI}booleanStringType"/&gt;
 *           &lt;element name="stringValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="dateTimeValue" type="{http://www.wldelft.nl/fews/PI}DateTimeComplexType"/&gt;
 *           &lt;element name="table" type="{http://www.wldelft.nl/fews/PI}GlobalTableComplexType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.wldelft.nl/fews/PI}idString" /&gt;
 *       &lt;attribute name="name" type="{http://www.wldelft.nl/fews/PI}idString" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelParameterComplexType", propOrder = {
    "description",
    "dblValue",
    "intValue",
    "boolValue",
    "stringValue",
    "dateTimeValue",
    "table"
})
public class ModelParameterComplexType {

    protected String description;
    @XmlSchemaType(name = "anySimpleType")
    protected String dblValue;
    @XmlSchemaType(name = "anySimpleType")
    protected String intValue;
    @XmlSchemaType(name = "anySimpleType")
    protected String boolValue;
    protected String stringValue;
    protected DateTimeComplexType dateTimeValue;
    protected GlobalTableComplexType table;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the dblValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDblValue() {
        return dblValue;
    }

    /**
     * Sets the value of the dblValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDblValue(String value) {
        this.dblValue = value;
    }

    /**
     * Gets the value of the intValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntValue() {
        return intValue;
    }

    /**
     * Sets the value of the intValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntValue(String value) {
        this.intValue = value;
    }

    /**
     * Gets the value of the boolValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoolValue() {
        return boolValue;
    }

    /**
     * Sets the value of the boolValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoolValue(String value) {
        this.boolValue = value;
    }

    /**
     * Gets the value of the stringValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStringValue() {
        return stringValue;
    }

    /**
     * Sets the value of the stringValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStringValue(String value) {
        this.stringValue = value;
    }

    /**
     * Gets the value of the dateTimeValue property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeComplexType }
     *     
     */
    public DateTimeComplexType getDateTimeValue() {
        return dateTimeValue;
    }

    /**
     * Sets the value of the dateTimeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeComplexType }
     *     
     */
    public void setDateTimeValue(DateTimeComplexType value) {
        this.dateTimeValue = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalTableComplexType }
     *     
     */
    public GlobalTableComplexType getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalTableComplexType }
     *     
     */
    public void setTable(GlobalTableComplexType value) {
        this.table = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
