//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.08 at 03:36:14 PM MST 
//


package nl.wldelft.fews;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.wldelft.fews package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TimeSeries_QNAME = new QName("http://www.wldelft.nl/fews/PI", "TimeSeries");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.wldelft.fews
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TimeSeriesCollectionComplexType }
     * 
     */
    public TimeSeriesCollectionComplexType createTimeSeriesCollectionComplexType() {
        return new TimeSeriesCollectionComplexType();
    }

    /**
     * Create an instance of {@link TimeStepComplexType }
     * 
     */
    public TimeStepComplexType createTimeStepComplexType() {
        return new TimeStepComplexType();
    }

    /**
     * Create an instance of {@link TimeStepUnitComplexType }
     * 
     */
    public TimeStepUnitComplexType createTimeStepUnitComplexType() {
        return new TimeStepUnitComplexType();
    }

    /**
     * Create an instance of {@link DateTimeComplexType }
     * 
     */
    public DateTimeComplexType createDateTimeComplexType() {
        return new DateTimeComplexType();
    }

    /**
     * Create an instance of {@link PropertiesComplexType }
     * 
     */
    public PropertiesComplexType createPropertiesComplexType() {
        return new PropertiesComplexType();
    }

    /**
     * Create an instance of {@link StringPropertyComplexType }
     * 
     */
    public StringPropertyComplexType createStringPropertyComplexType() {
        return new StringPropertyComplexType();
    }

    /**
     * Create an instance of {@link IntPropertyComplexType }
     * 
     */
    public IntPropertyComplexType createIntPropertyComplexType() {
        return new IntPropertyComplexType();
    }

    /**
     * Create an instance of {@link FloatPropertyComplexType }
     * 
     */
    public FloatPropertyComplexType createFloatPropertyComplexType() {
        return new FloatPropertyComplexType();
    }

    /**
     * Create an instance of {@link DoublePropertyComplexType }
     * 
     */
    public DoublePropertyComplexType createDoublePropertyComplexType() {
        return new DoublePropertyComplexType();
    }

    /**
     * Create an instance of {@link DateTimePropertyComplexType }
     * 
     */
    public DateTimePropertyComplexType createDateTimePropertyComplexType() {
        return new DateTimePropertyComplexType();
    }

    /**
     * Create an instance of {@link BoolPropertyComplexType }
     * 
     */
    public BoolPropertyComplexType createBoolPropertyComplexType() {
        return new BoolPropertyComplexType();
    }

    /**
     * Create an instance of {@link PeriodConditionComplexType }
     * 
     */
    public PeriodConditionComplexType createPeriodConditionComplexType() {
        return new PeriodConditionComplexType();
    }

    /**
     * Create an instance of {@link EnsembleMemberComplexType }
     * 
     */
    public EnsembleMemberComplexType createEnsembleMemberComplexType() {
        return new EnsembleMemberComplexType();
    }

    /**
     * Create an instance of {@link EnsembleMemberRangeComplexType }
     * 
     */
    public EnsembleMemberRangeComplexType createEnsembleMemberRangeComplexType() {
        return new EnsembleMemberRangeComplexType();
    }

    /**
     * Create an instance of {@link GlobalTableComplexType }
     * 
     */
    public GlobalTableComplexType createGlobalTableComplexType() {
        return new GlobalTableComplexType();
    }

    /**
     * Create an instance of {@link ColumnIdsComplexType }
     * 
     */
    public ColumnIdsComplexType createColumnIdsComplexType() {
        return new ColumnIdsComplexType();
    }

    /**
     * Create an instance of {@link ColumnMetaDataComplexType }
     * 
     */
    public ColumnMetaDataComplexType createColumnMetaDataComplexType() {
        return new ColumnMetaDataComplexType();
    }

    /**
     * Create an instance of {@link ColumnTypesComplexType }
     * 
     */
    public ColumnTypesComplexType createColumnTypesComplexType() {
        return new ColumnTypesComplexType();
    }

    /**
     * Create an instance of {@link RowComplexType }
     * 
     */
    public RowComplexType createRowComplexType() {
        return new RowComplexType();
    }

    /**
     * Create an instance of {@link ArchiveTimeSeriesSetComplexType }
     * 
     */
    public ArchiveTimeSeriesSetComplexType createArchiveTimeSeriesSetComplexType() {
        return new ArchiveTimeSeriesSetComplexType();
    }

    /**
     * Create an instance of {@link ModelParameterComplexType }
     * 
     */
    public ModelParameterComplexType createModelParameterComplexType() {
        return new ModelParameterComplexType();
    }

    /**
     * Create an instance of {@link TimeSeriesComplexType }
     * 
     */
    public TimeSeriesComplexType createTimeSeriesComplexType() {
        return new TimeSeriesComplexType();
    }

    /**
     * Create an instance of {@link HeaderComplexType }
     * 
     */
    public HeaderComplexType createHeaderComplexType() {
        return new HeaderComplexType();
    }

    /**
     * Create an instance of {@link ThresholdComplexType }
     * 
     */
    public ThresholdComplexType createThresholdComplexType() {
        return new ThresholdComplexType();
    }

    /**
     * Create an instance of {@link DomainAxisComplexType }
     * 
     */
    public DomainAxisComplexType createDomainAxisComplexType() {
        return new DomainAxisComplexType();
    }

    /**
     * Create an instance of {@link DomainAxisValuesComplexType }
     * 
     */
    public DomainAxisValuesComplexType createDomainAxisValuesComplexType() {
        return new DomainAxisValuesComplexType();
    }

    /**
     * Create an instance of {@link HighLevelThresholdsComplexType }
     * 
     */
    public HighLevelThresholdsComplexType createHighLevelThresholdsComplexType() {
        return new HighLevelThresholdsComplexType();
    }

    /**
     * Create an instance of {@link EventComplexType }
     * 
     */
    public EventComplexType createEventComplexType() {
        return new EventComplexType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeSeriesCollectionComplexType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wldelft.nl/fews/PI", name = "TimeSeries")
    public JAXBElement<TimeSeriesCollectionComplexType> createTimeSeries(TimeSeriesCollectionComplexType value) {
        return new JAXBElement<TimeSeriesCollectionComplexType>(_TimeSeries_QNAME, TimeSeriesCollectionComplexType.class, null, value);
    }

}
