//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.08 at 03:36:14 PM MST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.wldelft.nl/fews/PI", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.wldelft.fews;
