//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.08 at 03:36:14 PM MST 
//


package nl.wldelft.fews;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A period condition. If a date is specified without a timezone, e.g. 2002-10-10T12:00:00, then it is assumed to be in UTC.
 * 
 * <p>Java class for PeriodConditionComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PeriodConditionComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="timeZone" type="{http://www.wldelft.nl/fews/PI}TimeZoneSimpleType" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="startDate" type="{http://www.wldelft.nl/fews/PI}DateTimeComplexType"/&gt;
 *             &lt;element name="endDate" type="{http://www.wldelft.nl/fews/PI}DateTimeComplexType"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;element name="validBeforeDate" type="{http://www.wldelft.nl/fews/PI}DateTimeComplexType"/&gt;
 *           &lt;element name="validAfterDate" type="{http://www.wldelft.nl/fews/PI}DateTimeComplexType"/&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="startMonthDay" type="{http://www.w3.org/2001/XMLSchema}gMonthDay"/&gt;
 *             &lt;element name="endMonthDay" type="{http://www.w3.org/2001/XMLSchema}gMonthDay"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;element name="monthDay" type="{http://www.w3.org/2001/XMLSchema}gMonthDay" maxOccurs="unbounded"/&gt;
 *           &lt;element name="month" type="{http://www.w3.org/2001/XMLSchema}gMonth" maxOccurs="unbounded"/&gt;
 *           &lt;element name="day" type="{http://www.w3.org/2001/XMLSchema}gDay" maxOccurs="unbounded"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PeriodConditionComplexType", propOrder = {
    "timeZone",
    "startDate",
    "endDate",
    "validBeforeDate",
    "validAfterDate",
    "startMonthDay",
    "endMonthDay",
    "monthDay",
    "month",
    "day"
})
public class PeriodConditionComplexType {

    protected Double timeZone;
    protected DateTimeComplexType startDate;
    protected DateTimeComplexType endDate;
    protected DateTimeComplexType validBeforeDate;
    protected DateTimeComplexType validAfterDate;
    @XmlSchemaType(name = "gMonthDay")
    protected XMLGregorianCalendar startMonthDay;
    @XmlSchemaType(name = "gMonthDay")
    protected XMLGregorianCalendar endMonthDay;
    @XmlSchemaType(name = "gMonthDay")
    protected List<XMLGregorianCalendar> monthDay;
    @XmlSchemaType(name = "gMonth")
    protected List<XMLGregorianCalendar> month;
    @XmlSchemaType(name = "gDay")
    protected List<XMLGregorianCalendar> day;

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTimeZone(Double value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeComplexType }
     *     
     */
    public DateTimeComplexType getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeComplexType }
     *     
     */
    public void setStartDate(DateTimeComplexType value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeComplexType }
     *     
     */
    public DateTimeComplexType getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeComplexType }
     *     
     */
    public void setEndDate(DateTimeComplexType value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the validBeforeDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeComplexType }
     *     
     */
    public DateTimeComplexType getValidBeforeDate() {
        return validBeforeDate;
    }

    /**
     * Sets the value of the validBeforeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeComplexType }
     *     
     */
    public void setValidBeforeDate(DateTimeComplexType value) {
        this.validBeforeDate = value;
    }

    /**
     * Gets the value of the validAfterDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeComplexType }
     *     
     */
    public DateTimeComplexType getValidAfterDate() {
        return validAfterDate;
    }

    /**
     * Sets the value of the validAfterDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeComplexType }
     *     
     */
    public void setValidAfterDate(DateTimeComplexType value) {
        this.validAfterDate = value;
    }

    /**
     * Gets the value of the startMonthDay property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartMonthDay() {
        return startMonthDay;
    }

    /**
     * Sets the value of the startMonthDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartMonthDay(XMLGregorianCalendar value) {
        this.startMonthDay = value;
    }

    /**
     * Gets the value of the endMonthDay property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndMonthDay() {
        return endMonthDay;
    }

    /**
     * Sets the value of the endMonthDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndMonthDay(XMLGregorianCalendar value) {
        this.endMonthDay = value;
    }

    /**
     * Gets the value of the monthDay property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the monthDay property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMonthDay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLGregorianCalendar }
     * 
     * 
     */
    public List<XMLGregorianCalendar> getMonthDay() {
        if (monthDay == null) {
            monthDay = new ArrayList<XMLGregorianCalendar>();
        }
        return this.monthDay;
    }

    /**
     * Gets the value of the month property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the month property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMonth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLGregorianCalendar }
     * 
     * 
     */
    public List<XMLGregorianCalendar> getMonth() {
        if (month == null) {
            month = new ArrayList<XMLGregorianCalendar>();
        }
        return this.month;
    }

    /**
     * Gets the value of the day property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the day property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLGregorianCalendar }
     * 
     * 
     */
    public List<XMLGregorianCalendar> getDay() {
        if (day == null) {
            day = new ArrayList<XMLGregorianCalendar>();
        }
        return this.day;
    }

}
