//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.08 at 03:36:14 PM MST 
//


package nl.wldelft.fews;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Time series data represent data collected over a given period of time at a specific location
 * 
 * <p>Java class for TimeSeriesCollectionComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimeSeriesCollectionComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{http://www.wldelft.nl/fews/PI}TimeZoneChoice" minOccurs="0"/&gt;
 *         &lt;element name="series" type="{http://www.wldelft.nl/fews/PI}TimeSeriesComplexType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="version" type="{http://www.wldelft.nl/fews/PI}versionString" default="1.2" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeSeriesCollectionComplexType", propOrder = {
    "timeZone",
    "daylightSavingObservingTimeZone",
    "series"
})
@XmlRootElement(name="TimeSeries")
public class TimeSeriesCollectionComplexType {

    @XmlElement(defaultValue = "0.0")
    protected Double timeZone;
    @XmlSchemaType(name = "string")
    protected DaylightSavingObservedTimeZoneEnumStringType daylightSavingObservingTimeZone;
    @XmlElement(required = true)
    protected List<TimeSeriesComplexType> series;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTimeZone(Double value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the daylightSavingObservingTimeZone property.
     * 
     * @return
     *     possible object is
     *     {@link DaylightSavingObservedTimeZoneEnumStringType }
     *     
     */
    public DaylightSavingObservedTimeZoneEnumStringType getDaylightSavingObservingTimeZone() {
        return daylightSavingObservingTimeZone;
    }

    /**
     * Sets the value of the daylightSavingObservingTimeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaylightSavingObservedTimeZoneEnumStringType }
     *     
     */
    public void setDaylightSavingObservingTimeZone(DaylightSavingObservedTimeZoneEnumStringType value) {
        this.daylightSavingObservingTimeZone = value;
    }

    /**
     * Gets the value of the series property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the series property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSeries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeSeriesComplexType }
     * 
     * 
     */
    public List<TimeSeriesComplexType> getSeries() {
        if (series == null) {
            series = new ArrayList<TimeSeriesComplexType>();
        }
        return this.series;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.2";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
