//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.08 at 03:36:14 PM MST 
//


package nl.wldelft.fews;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * The time unit element has three attributes, unit and divider and multiplier. the unit is second, minute, hour, week, month year. The divider attribute is optional (default = 1).
 * 
 * <p>Java class for TimeStepComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimeStepComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="unit" type="{http://www.wldelft.nl/fews/PI}timeStepUnitEnumStringType" /&gt;
 *       &lt;attribute name="divider" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="1" /&gt;
 *       &lt;attribute name="multiplier" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="1" /&gt;
 *       &lt;attribute name="times" type="{http://www.wldelft.nl/fews/PI}shortTimeListType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeStepComplexType")
public class TimeStepComplexType {

    @XmlAttribute(name = "unit")
    protected TimeStepUnitEnumStringType unit;
    @XmlAttribute(name = "divider")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger divider;
    @XmlAttribute(name = "multiplier")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger multiplier;
    @XmlAttribute(name = "times")
    protected String times;

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link TimeStepUnitEnumStringType }
     *     
     */
    public TimeStepUnitEnumStringType getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeStepUnitEnumStringType }
     *     
     */
    public void setUnit(TimeStepUnitEnumStringType value) {
        this.unit = value;
    }

    /**
     * Gets the value of the divider property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDivider() {
        if (divider == null) {
            return new BigInteger("1");
        } else {
            return divider;
        }
    }

    /**
     * Sets the value of the divider property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDivider(BigInteger value) {
        this.divider = value;
    }

    /**
     * Gets the value of the multiplier property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMultiplier() {
        if (multiplier == null) {
            return new BigInteger("1");
        } else {
            return multiplier;
        }
    }

    /**
     * Sets the value of the multiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMultiplier(BigInteger value) {
        this.multiplier = value;
    }

    /**
     * Gets the value of the times property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimes() {
        return times;
    }

    /**
     * Sets the value of the times property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimes(String value) {
        this.times = value;
    }

}
