//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.08 at 03:36:14 PM MST 
//


package nl.wldelft.fews;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * Time series data represent data collected over a given
 *                 period of time at a specific location
 * 
 * <p>Java class for TimeSeriesComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimeSeriesComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="header" type="{http://www.wldelft.nl/fews/PI}HeaderComplexType"/&gt;
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element name="properties" type="{http://www.wldelft.nl/fews/PI}PropertiesComplexType" minOccurs="0"/&gt;
 *           &lt;element name="domainAxisValues" type="{http://www.wldelft.nl/fews/PI}DomainAxisValuesComplexType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="event" type="{http://www.wldelft.nl/fews/PI}EventComplexType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element name="comment" type="{http://www.wldelft.nl/fews/PI}commentString" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeSeriesComplexType", propOrder = {
    "header",
    "propertiesAndDomainAxisValuesAndEvent",
    "comment"
})
public class TimeSeriesComplexType {

    @XmlElement(required = true)
    protected HeaderComplexType header;
    @XmlElements({
        @XmlElement(name = "properties", type = PropertiesComplexType.class),
        @XmlElement(name = "domainAxisValues", type = DomainAxisValuesComplexType.class),
        @XmlElement(name = "event", type = EventComplexType.class)
    })
    protected List<Object> propertiesAndDomainAxisValuesAndEvent;
    protected String comment;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderComplexType }
     *     
     */
    public HeaderComplexType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderComplexType }
     *     
     */
    public void setHeader(HeaderComplexType value) {
        this.header = value;
    }

    /**
     * Gets the value of the propertiesAndDomainAxisValuesAndEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertiesAndDomainAxisValuesAndEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertiesAndDomainAxisValuesAndEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertiesComplexType }
     * {@link DomainAxisValuesComplexType }
     * {@link EventComplexType }
     * 
     * 
     */
    public List<Object> getPropertiesAndDomainAxisValuesAndEvent() {
        if (propertiesAndDomainAxisValuesAndEvent == null) {
            propertiesAndDomainAxisValuesAndEvent = new ArrayList<Object>();
        }
        return this.propertiesAndDomainAxisValuesAndEvent;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

}
